services:
  - type: web
    name: dental-funnel-app
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: CORS_ORIGIN
        value: "https://dental-funnel-nvoc4saot-balasim-jasim-s-projects.vercel.app"
